In [1]:
pip install numpy


In [2]:
import numpy as np

In [5]:
#Function 1
x=np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
#Function 2 MultiDimentional Array with all zeros
y=np.zeros((6,6))
y

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
#Function 3 extraction of all odd numbers from array
z=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
z[z % 2==2]
##########


array([], dtype=int32)

In [18]:
#Function 4 Reverse Raw in array
z=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
z[::-1,]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [20]:
#Function 5 Reverse Raw and column in array
Data =([1,2,3,4],[5,6,7,8])
X=np.array(Data)
X[::-1,::-1]


array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [21]:
#Function 6 Size of array
list=(1,5,6,9,8)
arr=np.array(list)
print("Size:",arr.size)

Size: 5


In [22]:
#Function 7 find common in arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [24]:
#Function 8 mean of arrays
a = np.array([1,2,3,4,5])
print("Mean value is :", a.mean())


Mean value is : 3.0


In [26]:
#Function 9 Maximum of arrays
x = np.array([1,2,3,4,5,6,7,8,9,20,10,12,18])
print("Max value is :", x.max())

Max value is : 20


In [28]:
#Function 10 Minimum of arrays
y = np.array([2,3,4,5,6,7,8,9,20,12,17])
print("Min value is :", y.min())


Min value is : 2


In [31]:
#Function 11 Median of arrays
print("Median value is :", np.median(y))

Median value is : 7.0


In [36]:
#Function 12 Standard Deviation of arrays
y = np.array([1,2,3,4,5,6,7,8,9,20,13,18,17])
print("SD value is :", np.std(y))

SD value is : 6.106549011381335


In [68]:
#Function 13 2D arrays
b = np.arange(64).reshape(8,8)
print(b)


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


In [67]:
#Function 14 3D arrays
a = np.arange(32).reshape(2,4,4)  
print(a)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [65]:
#Function 15 no. of Dimintion of array
y = np.array([1, 2, 3,4])
y.ndim


1

In [43]:
#Function 17 array size
x = np.array([1,2,3], dtype=np.float32)
x.itemsize


4

In [45]:
#Function 18 array type
x = np.array ([1,2,3])
print(x.dtype)


int32


In [47]:
#Function 19 array Size
y = np.array([(1,2,3,4,5,6,9,3,4)])
print(y.size)


9


In [48]:
#Function 20 Slicing
x = np.array([(1,2,3,4),(3,4,5,6)])
print(x[0:,3])


[4 6]


In [69]:
#Function 21 multiple time array
g = b*2
g


array([[  0,   2,   4,   6,   8,  10,  12,  14],
       [ 16,  18,  20,  22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40,  42,  44,  46],
       [ 48,  50,  52,  54,  56,  58,  60,  62],
       [ 64,  66,  68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90,  92,  94],
       [ 96,  98, 100, 102, 104, 106, 108, 110],
       [112, 114, 116, 118, 120, 122, 124, 126]])

In [77]:
#Function 22 minus
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)

[[0 0 0]
 [0 0 0]]


In [78]:
#Function 23 Multiply
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x*y)

[[ 1  4  9]
 [ 9 16 25]]


In [79]:
#Function 24 Division
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x/y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [80]:
#Function 25 
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


In [81]:
#Function 26 
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


In [87]:
#Function 27 Odd numbers from Arrays
f = np.arange(20)
f[f%2 == 0] =0  
f


array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [89]:
#Function 28 Divide in to two arrays
g = np.arange(64)
h = np.reshape(g, (2, -1))
h

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [91]:
#Function 29
b[(b >= 8) & (b <= 20)]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [93]:
#Function 30
arr = np.arange(12).reshape(4,3)
arr[:,[1,0,2]]

array([[ 1,  0,  2],
       [ 4,  3,  5],
       [ 7,  6,  8],
       [10,  9, 11]])

In [94]:
#Function 31 Sin of Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sin(arr))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [95]:
#Function 32 Cos of Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.cos(arr))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [97]:
#Function 33 Theta of Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.tan(arr))

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]


In [98]:
#Function 34 Random of Array
i = np.random.random(11)
i[i.argmax()]=0
i

array([0.        , 0.08731531, 0.47656464, 0.59806362, 0.74334629,
       0.14034167, 0.32654431, 0.09386393, 0.52854231, 0.05228074,
       0.43553912])

In [99]:
#Function 35 Round
np.round(18.09545, 1), round(18.0554, 2),round(18.0554, 3)

(18.1, 18.06, 18.055)

In [100]:
#Function 36 Floor
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [101]:
#Function 37 Ceil
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [102]:
#Function 38 Product of two dimintial array
np.prod([[1.,2.],[3.,4.]])

24.0

In [106]:
#Function 39 LCM
np.lcm(12, 20,)

60

In [108]:
#Function 40 Capitalization
b = np.array(['a1b2','1b2a','b2a1','2a1b'],'S4');
np.char.capitalize(b)


array([b'A1b2', b'1b2a', b'B2a1', b'2a1b'], dtype='|S4')

In [110]:
#Function 41 Sort
a = np.array([[1,4], [3,1]])
a

array([[1, 4],
       [3, 1]])

In [111]:
#Function 42 Variance
a = np.array([[1, 2], [3, 4]])
np.var(a)

1.25

In [112]:
#Function 43 replace missing values
arr2 = np.random.randint(3,70)
arr2 = np.nan  # not a number
arr2

nan

In [113]:
#Function 44 Cummulative sum
arr2 = np.arange(1,10)
np.cumsum(arr2)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [116]:
#Function 45 Percetile
a=np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11],[12, 13, 14]])
np.percentile(a,95)

13.299999999999999

In [117]:
#Function 46 find null value of array
np.isnan(a)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [119]:
#Function 47 Power
np.power(100, 2)

10000

In [120]:
#Function 48  Random random
arr = np.random.randn(4, 4)
arr

array([[-0.36219717, -0.59779044,  1.01571878, -1.11021692],
       [-0.95780658, -2.53716881, -1.14022763,  0.97211628],
       [ 0.82992708,  0.28660993, -0.61682104, -1.06716525],
       [ 1.31499493,  1.88421047, -0.9251834 , -1.38275516]])

In [121]:
#Function 49 Replace Values
np.where(arr >0, 2, -2)

array([[-2, -2,  2, -2],
       [-2, -2, -2,  2],
       [ 2,  2, -2, -2],
       [ 2,  2, -2, -2]])

In [122]:
#Function 50 find Unique in Array
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])